@startuml
actor Admin_PL
participant System

Admin_PL -> System: removeMember(signId, projectId, removeMemberId)
alt member not found
    System --> Admin_PL: Error msg("존재하지 않는 사용자입니다.")
else
    alt project not found
        System --> Admin_PL: Error msg("존재하지 않는 프로젝트입니다.")
    else
        alt member not found
            System --> Admin_PL: Error msg("존재하지 않는 사용자입니다.")
        else
            alt is PL
                System -> System: set project leader null
            else
                alt removing PL
                    System --> Admin_PL: Error msg("프로젝트 리더는 프로젝트 리더를 삭제할 수 없습니다.")
                else
                    System -> System: removeMember
                    System --> Admin_PL: return ProjectResponseDto(id, name, members, issues, leaderId)
                end
            end
        end
    end
end
@enduml
