@startuml
actor Admin
participant System

Admin -> System: removeProject(signId, projectId)
alt member not found
    System --> Admin: Error msg("존재하지 않는 사용자입니다.")
else
    alt project not found
        System --> Admin: Error msg("존재하지 않는 프로젝트입니다.")
    else
        alt not ADMIN
            System --> Admin: Error msg("관리자가 아닙니다.")
        else
            System -> System: set project as deleted
            System -> System: find project members
            System -> System: set members as deleted
            System -> System: find project issues
            System -> System: set issues as deleted
            System --> Admin: return void
        end
    end
end
@enduml
