@startuml
actor Dev
participant System

Dev -> System: updateIssueDev(signId, issueId, status)
alt member not found
    System --> Dev: Error msg("존재하지 않는 사용자입니다.")
else
    alt issue not found
        System --> Dev: Error msg("존재하지 않는 이슈입니다.")
    else
        alt project not found
            System --> Dev: Error msg("존재하지 않는 프로젝트입니다.")
        else
            alt not DEV
                System --> Dev: Error msg("개발자만 상태변경 기능을 사용가능합니다.")
            else
                alt not owner
                    System --> Dev: Error msg("본인에게 할당된 이슈의 상태만 수정할 수 있습니다.")
                else
                    System -> System: update issue status
                    System -> System: create comment for status update
                    System --> Dev: return IssueResponseDto(id, title, description, reporter, project, status, priority, category)
                end
            end
        end
    end
end
@enduml
