@startuml
actor Admin
participant System
participant DBMS as "Database"

Admin -> System: removeProject(signId, projectId)
System -> DBMS: validateMember(signId)
System -> DBMS: validateAdmin(signId)
System -> DBMS: validateProject(projectId)
System -> DBMS: removeProject(projectId)
System -> Admin: "removed"
@enduml
