@startuml
actor Admin
participant System
participant DBMS as "Database"

Admin -> System: findMembersByRole(signId, projectId, role)
System -> DBMS: validateMember(signId)
System -> DBMS: validateProject(projectId)
System -> DBMS: isMemberOfProject(signId, projectId)
System -> DBMS: validateAdminOrPL(signId)
System -> DBMS: getProjectMembersByRole(projectId, role)
System -> Admin: List<MemberResponseDto
@enduml
