@startuml
actor TEST
participant System
participant DBMS as "Database"

TEST -> System: createComment(signId, commentCreateRequestDto)
System -> DBMS: validateMember(signId)
System -> DBMS: validateIssue(commentCreateRequestDto.getIssueId)
System -> DBMS: validateProject(issue.projectId)
System -> DBMS: isMemberOfProject(signId, issue.projectId)
System -> DBMS: saveComment(issueId, signId, content)
System -> TEST: CommentResponseDto
@enduml
