@startuml
actor TEST
participant System
participant DBMS as "Database"

TEST -> System: getComments(signId, issueId)
System -> DBMS: validateMember(signId)
System -> DBMS: validateIssue(issueId)
System -> DBMS: validateProject(issue.projectId)
System -> DBMS: isMemberOfProject(signId, issue.projectId)
System -> DBMS: getComments(issueId)
System -> TEST: List<CommentResponseDto
@enduml
